CMAKE_MINIMUM_REQUIRED(VERSION 3.5)

if(LUNACAT_DOWNLOADS_SILENT)
    SET(LUNACAT_GIT_PROGRESS FALSE)
    SET(LUNACAT_DOWNLOAD_NO_PROGRESS 1)
    SET(LUNACAT_FILE_DOWNLOAD_SHOW_PROGRESS FALSE)
else()
    SET(LUNACAT_GIT_PROGRESS TRUE)
    SET(LUNACAT_DOWNLOAD_NO_PROGRESS 0)
    SET(LUNACAT_FILE_DOWNLOAD_SHOW_PROGRESS TRUE)
endif()

MESSAGE("LUNACAT_DOWNLOADS_SILENT: " ${LUNACAT_DOWNLOADS_SILENT})
MESSAGE("LUNACAT_GIT_PROGRESS: " ${LUNACAT_GIT_PROGRESS})
MESSAGE("LUNACAT_DOWNLOAD_NO_PROGRESS: " ${LUNACAT_DOWNLOAD_NO_PROGRESS})
MESSAGE("LUNACAT_FILE_DOWNLOAD_SHOW_PROGRESS: " ${LUNACAT_FILE_DOWNLOAD_SHOW_PROGRESS})

include(ExternalProject)

find_package(Git REQUIRED)

macro(LUNACAT_DOWNLOAD_FILE NAME URL FILE)
    if(NOT EXISTS ${LUNACAT_DEPENDENCIES_SOURCE_DIRECTORY}/${NAME}/${FILE})
        if(LUNACAT_FILE_DOWNLOAD_SHOW_PROGRESS)
            file(DOWNLOAD ${URL} ${LUNACAT_DEPENDENCIES_SOURCE_DIRECTORY}/${NAME}/${FILE} SHOW_PROGRESS)
        else()
            file(DOWNLOAD ${URL} ${LUNACAT_DEPENDENCIES_SOURCE_DIRECTORY}/${NAME}/${FILE})
        endif()
    endif()
endmacro()

macro(LUNACAT_DOWNLOAD_URL NAME URL)
    ExternalProject_Add(${NAME}_download PREFIX ${NAME}
        SOURCE_DIR ${LUNACAT_DEPENDENCIES_SOURCE_DIRECTORY}/${NAME}
        
        URL ${URL}
        DOWNLOAD_NO_PROGRESS ${LUNACAT_DOWNLOAD_NO_PROGRESS}

        CONFIGURE_COMMAND ""
        BUILD_COMMAND ""
        UPDATE_COMMAND ""
        INSTALL_COMMAND ""
    )
    
    add_library(${NAME} STATIC IMPORTED)
endmacro()

macro(LUNACAT_DOWNLOAD_URL_HASH NAME URL HASH_ALGO HASH)
    ExternalProject_Add(${NAME}_download PREFIX ${NAME}
        SOURCE_DIR ${LUNACAT_DEPENDENCIES_SOURCE_DIRECTORY}/${NAME}
        
        URL ${URL}
        URL_HASH ${HASH_ALGO}=${HASH}
        DOWNLOAD_NO_PROGRESS ${LUNACAT_DOWNLOAD_NO_PROGRESS}

        CONFIGURE_COMMAND ""
        BUILD_COMMAND ""
        UPDATE_COMMAND ""
        INSTALL_COMMAND ""
    )
    
    add_library(${NAME} STATIC IMPORTED)
endmacro()

macro(LUNACAT_GIT_CLONE NAME REPOSITORY)
    set(TAG ${ARGN})
    
    list(LENGTH TAG EXIST_TAG)
    
    if(${EXIST_TAG} GREATER 0)
        ExternalProject_Add( "${NAME}_${TAG}_download" PREFIX ${NAME}
            SOURCE_DIR ${LUNACAT_DEPENDENCIES_SOURCE_DIRECTORY}/${NAME}
            
            GIT_REPOSITORY ${REPOSITORY}
            GIT_TAG ${TAG}
            GIT_PROGRESS ${LUNACAT_GIT_PROGRESS}

            CONFIGURE_COMMAND ""
            BUILD_COMMAND ""
            UPDATE_COMMAND ""
            INSTALL_COMMAND ""
        )
    else()
        ExternalProject_Add(${NAME}_download PREFIX ${NAME}
            SOURCE_DIR ${LUNACAT_DEPENDENCIES_SOURCE_DIRECTORY}/${NAME}
            
            GIT_REPOSITORY ${REPOSITORY}
            GIT_PROGRESS ${LUNACAT_GIT_PROGRESS}

            CONFIGURE_COMMAND ""
            BUILD_COMMAND ""
            UPDATE_COMMAND ${GIT_EXECUTABLE} pull
            INSTALL_COMMAND ""
            )
    endif()
    
    add_library(${NAME} STATIC IMPORTED)
endmacro()