CMAKE_MINIMUM_REQUIRED(VERSION 3.5)

IF(CMAKE_BUILD_TYPE MATCHES "Debug")
    SET(LUNACAT_BUILD_TYPE_DEBUG 1)
ELSEIF(CMAKE_BUILD_TYPE MATCHES "RelWithDebInfo")
    SET(LUNACAT_BUILD_TYPE_RELWITHDEBINFO 1)
ELSEIF(CMAKE_BUILD_TYPE MATCHES "Release")
    SET(LUNACAT_BUILD_TYPE_RELEASE 1)
ENDIF()

MACRO(LUNACAT_ADD_FILTER group_name)
    SOURCE_GROUP(${group_name} FILES ${ARGN})
    SET(LUNACAT_SOURCE_FILES ${LUNACAT_SOURCE_FILES} ${ARGN})
ENDMACRO()

MACRO(LUNACAT_ADD_LIBRARY)
    ADD_LIBRARY(${PROJECT_NAME} STATIC ${LUNACAT_SOURCE_FILES})
    
    set_target_properties(${PROJECT_NAME} PROPERTIES LINKER_LANGUAGE C)
ENDMACRO()

MACRO(LUNACAT_LINK_DEPENDENCIES_LIBRARY NAME)
    TARGET_LINK_LIBRARIES(${PROJECT_NAME} "${LUNACAT_DEPENDENCIES_LIBRARY_DIRECTORY}/${CMAKE_STATIC_LIBRARY_PREFIX}${NAME}${CMAKE_STATIC_LIBRARY_SUFFIX}")
ENDMACRO()


MACRO(LUNACAT_ADD_EXECUTABLE)
    IF(LUNACAT_TARGET_OSX)
        ADD_EXECUTABLE(${PROJECT_NAME} MACOSX_BUNDLE ${LUNACAT_SOURCE_FILES})
    ELSEIF(LUNACAT_TARGET_WIN32)
        ADD_EXECUTABLE(${PROJECT_NAME} WIN32 ${LUNACAT_SOURCE_FILES})
    ELSEIF(LUNACAT_TARGET_UNIX)
        ADD_EXECUTABLE(${PROJECT_NAME} ${LUNACAT_SOURCE_FILES})
    ENDIF()
    
    set_target_properties(${PROJECT_NAME} PROPERTIES LINKER_LANGUAGE C)
ENDMACRO()